### ISSUE TITLE
.ply files for pointcloud.py taking forever to finish

### ISSUE THREAD

**Issue by dsvilarkovic** [chrdiller/mitsuba-visualize#1]
Hello, I've just tried generating my pointcloud representation in .ply format by using your pointcloud.py and it seems it takes forever for it to run even though it. I am not able to debug it and I've checked everything, but it seems it never stops running, it's been on for 10 hours already. Is there something I am missing? Do you have any documentation or previous issue list so I can look and see how to fix it?

**Comment by chrdiller** [comment]
Hi, interesting, I've never encountered that. 
How many points are you trying to render? I usually used the script to render a few hundred points, my guess is that mitsuba is just working very slowly. 
How many samples and workers are you using? Do you see any additional output?

**Comment by dsvilarkovic** [comment]
I am rendering one sample at the time, pointcloud of size of 3000, using num_workers = 8 as I can see. I also generated mesh using mesh.py for the same object, and it took me 2-4 minutes.

Output looks like this after 5 hours of running (I had one with 10 hours, I stopped it):
![Screenshot from 2020-09-27 21-44-27](https://user-images.githubusercontent.com/18049803/94374172-bc934180-010a-11eb-8baa-23f5dea323eb.png)

Pointcloud rendered is one of the objects from ShapeNet dataset.

**Comment by chrdiller** [comment]
I see, could you also try rendering fewer points just for debug purposes? Really the only reason I can think of is that since Mitsuba runs entirely on the CPU it can't deal with that many spheres at once in a reasonable time frame.

If you have a GPU available it might make more sense in your case to render using cycles in blender with the point cloud plugin (https://github.com/uhlik/bpy).
